---
- name: Copy drives init tools
  copy:
    src: "init_drive.sh"
    dest: "{{ sp_toolsdir }}"
    mode: 0755

# temporary patch for auto-test-cluster: begin
- name: Init drives
  command: >
    /usr/local/bin/initdisks
  changed_when: false
# temporary patch for auto-test-cluster: end

- name: Get needed number of server instances
  script: get_instances.py
  args:
    executable: "{{ sp_python_executable }}"
  changed_when: false
  register: sp_instances

- name: Stop server instances
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  changed_when: false
  with_items: "{{ sp_instances.stdout_lines }}"

- name: Stop storpool_nvmed
  systemd:
    name: storpool_nvmed
    state: stopped
    enabled: no
  changed_when: false
  when:
    - sp_roles.nvme

- name: Expose all NVMe drives
  command: "{{ sp_expose_nvme_drives }}"
  changed_when: false
  ignore_errors: yes
  when:
    - sp_roles.nvme

- name: Settle udev
  command: udevadm settle
  changed_when: false

- name: Assign drives to servers
  shell: |
    set -o pipefail
    {{ sp_multi_server_helper }} -i {{ sp_server_instances }} \
    | bash
  changed_when: false
  tags:
    - skip_ansible_lint
