---
- name: Get StorPool interfaces
  shell: |
    {{ sp_showconf }} -n -e -- SP_IFACE1_CFG SP_IFACE2_CFG \
    | cut -d: -f2 \
    | cut -d. -f1
  changed_when: false
  args:
    executable: /bin/bash
  register: sp_interfaces
  tags:
    - skip_ansible_lint

- name: Check if StorPool uses bond interfaces
  set_fact:
    sp_bonding: "{{ true if sp_interfaces.stdout_lines | select('match', 'bond') | list | count > 0 else false }}"

- name: Get StorPool bond interface
  shell: |
    {{ sp_showconf }} -n -e -- SP_IFACE1_CFG \
    | cut -d: -f2 \
    | cut -d. -f1
  changed_when: false
  register: sp_bond
  when:
    - sp_bonding
  tags:
    - skip_ansible_lint

- name: Include distro-specific tasks
  include_tasks: "subtasks/bond_adjustments_{{ ansible_os_family | lower }}.yml"
