---
distro_deps:
  - cpupowerutils
  - "{{ 'libcgroup-tools' if ansible_distribution_major_version != '6' else 'less' }}"
  - lz4
  - mcelog
  - perf
  - perl-core
  - smartmontools
  - tuned
  - vim-enhanced

selinux_state: disabled
tuned_profile: throughput-performance
